# -*- coding: utf-8 -*-
"""HR Attrition Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tIVfvWtHMbDPtjeK-A8vbY4U-cTvCGd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/HR-Employee-Attrition.csv.xls')

# Display first 5 rows
df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.isnull().sum().sort_values(ascending=False)

print("Duplicate Rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)

print("Duplicates Removed")

print("Total Employees:", len(df))
df['Attrition'].value_counts()
(df['Attrition'].value_counts(normalize=True)*100).round(2)

plt.figure(figsize=(6,4))

sns.countplot(x='Attrition', data=df)

plt.title('Employee Attrition Distribution')
plt.show()

plt.figure(figsize=(6,4))

sns.countplot(x='Gender', data=df)

plt.title('Gender Distribution')
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(y='Department', data=df)

plt.title('Department Wise Employees')
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    x='Department',
    hue='Attrition',
    data=df
)

plt.title('Attrition by Department')
plt.xticks(rotation=20)
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(
    df['MonthlyIncome'],
    bins=30,
    kde=True
)

plt.title('Monthly Income Distribution')
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(
    df['Age'],
    bins=20,
    kde=True
)

plt.title('Age Distribution')
plt.show()

plt.figure(figsize=(6,4))

sns.countplot(
    x='OverTime',
    hue='Attrition',
    data=df
)

plt.title('Overtime vs Attrition')
plt.show()

plt.figure(figsize=(12,6))

sns.countplot(
    y='JobRole',
    hue='Attrition',
    data=df
)

plt.title('Attrition by Job Role')
plt.show()

numeric_df = df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(12,8))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x='Attrition',
    y='MonthlyIncome',
    data=df
)

plt.title('Monthly Income vs Attrition')
plt.show()

print("Attrition Count")
print(df['Attrition'].value_counts())

print("\nDepartment Wise Attrition")
print(df.groupby('Department')['Attrition'].value_counts())

print("\nOverTime Wise Attrition")
print(df.groupby('OverTime')['Attrition'].value_counts())

df.groupby('Department')['Attrition'].value_counts()
df.groupby('Gender')['Attrition'].value_counts()
df.groupby('OverTime')['Attrition'].value_counts()
df.groupby('JobRole')['Attrition'].value_counts()

df.to_csv('HR_Attrition_Cleaned.csv', index=False)

print("Cleaned Dataset Saved Successfully")

from google.colab import files

files.download('HR_Attrition_Cleaned.csv')